package ohos_app_cangjie_entry.ui.theme

import kit.ArkUI.*

public let TYPE_HEADLINE_LARGE: Float64 = 32.0
public let TYPE_HEADLINE_MEDIUM: Float64 = 28.0
public let TYPE_HEADLINE_SMALL: Float64 = 24.0
public let TYPE_TITLE_LARGE: Float64 = 22.0
public let TYPE_TITLE_MEDIUM: Float64 = 16.0
public let TYPE_TITLE_SMALL: Float64 = 14.0
public let TYPE_BODY_LARGE: Float64 = 16.0
public let TYPE_BODY_MEDIUM: Float64 = 14.0
public let TYPE_BODY_SMALL: Float64 = 12.0
public let TYPE_LABEL_LARGE: Float64 = 14.0
public let TYPE_LABEL_MEDIUM: Float64 = 12.0
public let TYPE_LABEL_SMALL: Float64 = 11.0
public let WEIGHT_SEMIBOLD = FontWeight.W600
public let WEIGHT_BOLD = FontWeight.W700